/**
 * Phosphor Icons mapping.
 * Maps our internal icon names to Phosphor React components.
 */
import type { Icon as PhIcon } from '@phosphor-icons/react';
import {
  Gauge,
  ShieldCheck,
  GameController,
  AppWindow,
  EyeSlash,
  Crosshair,
  Moon,
  WifiSlash,
  WarningCircle,
  TreeStructure,
  Monitor,
  Sparkle,
  HardDrives,
  MagnifyingGlass,
  GearSix,
  BatteryFull,
  Printer,
  Database,
  Cpu,
  Circuitry,
  Trash,
  XSquare,
  DownloadSimple,
  GlobeSimple,
  Image,
  Compass,
  FileText,
  Stack,
  TextAlignLeft,
  LockSimple,
  BellSlash,
  House,
  SlidersHorizontal,
  Clock,
  RocketLaunch,
  ArrowSquareOut,
  ArrowClockwise,
  Check,
  Thermometer,
  CaretRight,
  Plus,
  Info,
  Funnel,
  X,
  Palette,
  Keyboard,
  SpeakerSlash,
  Eye,
  List,
  Package,
  Cloud,
} from '@phosphor-icons/react';

export const ICONS: Record<string, PhIcon> = {
  bolt:         Gauge,
  zap:          Gauge,
  gauge:        Gauge,
  shield:       ShieldCheck,
  shield2:      ShieldCheck,
  gamepad:      GameController,
  window:       AppWindow,
  'eye-off':    EyeSlash,
  target:       Crosshair,
  moon:         Moon,
  'wifi-off':   WifiSlash,
  alert:        WarningCircle,
  network:      TreeStructure,
  monitor:      Monitor,
  sparkles:     Sparkle,
  'hard-drive': HardDrives,
  search:       MagnifyingGlass,
  cog:          GearSix,
  battery:      BatteryFull,
  printer:      Printer,
  database:     Database,
  cpu:          Cpu,
  memory:       Circuitry,
  trash:        Trash,
  'x-square':   XSquare,
  download:     DownloadSimple,
  globe:        GlobeSimple,
  image:        Image,
  compass:      Compass,
  'file-text':  FileText,
  layers:       Stack,
  'align-left': TextAlignLeft,
  lock:         LockSimple,
  'bell-off':   BellSlash,
  home:         House,
  sliders:      SlidersHorizontal,
  clock:        Clock,
  rocket:       RocketLaunch,
  external:     ArrowSquareOut,
  refresh:      ArrowClockwise,
  check:        Check,
  thermo:       Thermometer,
  chevron:      CaretRight,
  plus:         Plus,
  info:         Info,
  filter:       Funnel,
  x:            X,
  palette:      Palette,
  keyboard:     Keyboard,
  'volume-off': SpeakerSlash,
  eye:          Eye,
  menu:         List,
  package:      Package,
  cloud:        Cloud,
};
